# ----
# Site

title: Thinkware API Documentation
description: Thinkware API Documentation
url: http://apidocs.thinkwareinc.com
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
  sso:
    title: SSO
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
